MAILGUN_SMTP_LOGIN: postmaster@app707c8edcc09b477599eabec7a76918c7.mailgun.org
MAILGUN_SMTP_SERVER: smtp.mailgun.org
MAILGUN_API_KEY: key-7h1n91t2e4v2o45xm-ieyfutv6zvm8t0
MAILGUN_SMTP_PORT: 587
MAILGUN_SMTP_PASSWORD: 3goybfd5h2l6
ROLLBAR_ENDPOINT: https://api.rollbar.com/api/1/item/
ROLLBAR_ACCESS_TOKEN: 6ff45e3edc014b69ba42c6de3489732f
MONGOLAB_URI: mongodb://AddonList_app_99828e59-709a-4513-bfca-e9bdaef942f3:ov054ago5vkdsbqo6bc55hhv8t@ds053188.mongolab.com:53188/AddonList_app_99828e59-709a-4513-bfca-e9bdaef942f3
ADDONS_API_ID: app_99828e59-709a-4513-bfca-e9bdaef942f3
ADDONS_AUTH_TOKEN: uGw66h3rKwRBOytE4WUZ6g
