MAILGUN_SMTP_LOGIN: postmaster@app0582dc0621624f5c8768e735631f3d8f.mailgun.org
MAILGUN_SMTP_SERVER: smtp.mailgun.org
MAILGUN_API_KEY: key-8titsfrq7fse10x2qhnyjkokyhu5u0n2
MAILGUN_SMTP_PORT: 587
MAILGUN_SMTP_PASSWORD: 8u1n70rjqb25
ADDONS_API_ID: app_d6b82417-615c-43b4-9f7c-1cc53cc0a630
ADDONS_AUTH_TOKEN: an2JqrY-haN26NuFxLy5XA
