MAILGUN_SMTP_LOGIN: postmaster@app707c8edcc09b477599eabec7a76918c7.mailgun.org
MAILGUN_SMTP_SERVER: smtp.mailgun.org
MAILGUN_API_KEY: key-7h1n91t2e4v2o45xm-ieyfutv6zvm8t0
MAILGUN_SMTP_PORT: 587
MAILGUN_SMTP_PASSWORD: 3goybfd5h2l6
ADDONS_API_ID: app_99828e59-709a-4513-bfca-e9bdaef942f3
ADDONS_AUTH_TOKEN: uGw66h3rKwRBOytE4WUZ6g
