MONGOLAB_URI: mongodb://AddonList_app_97308f3f-948a-4f90-879a-ea3155e5f6d7:a9v96g3k0nh2o8j2sptsj9ijn2@ds047387.mongolab.com:47387/AddonList_app_97308f3f-948a-4f90-879a-ea3155e5f6d7
README_DOCS_URL: http://undefined.readme.io
README_DASH_URL: http://readme.io/project/undefined/v1.0/settings
MAILGUN_SMTP_LOGIN: postmaster@app7d41aa77b66a469180084fdaba10ecd8.mailgun.org
MAILGUN_SMTP_SERVER: smtp.mailgun.org
MAILGUN_API_KEY: key-5ovgg0arojrp4a4t5pzkff5r8dpoysi3
MAILGUN_SMTP_PORT: 587
MAILGUN_SMTP_PASSWORD: 2i776wvn6vk5
ADDONS_APP_ID: app_97308f3f-948a-4f90-879a-ea3155e5f6d7
ADDONS_APP_TOKEN: pyw5WBzdfFBh5ta5K63g
